// <auto-generated />
using System;
using BookingManagmentSystem.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingManagmentSystem.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928225604_AddBookings")]
    partial class AddBookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RentalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServicesCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "StartTime", "EndTime");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_HourlyRate", "[HourlyRate] >= 0");

                            t.HasCheckConstraint("CK_Bookings_RentalCost", "[RentalCost] >= 0");

                            t.HasCheckConstraint("CK_Bookings_ServicesCost", "[ServicesCost] >= 0");

                            t.HasCheckConstraint("CK_Bookings_TimeRange", "[EndTime] > [StartTime]");
                        });
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.BookingServices", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookingId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingServices", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingServices_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Halls", null, t =>
                        {
                            t.HasCheckConstraint("CK_Halls_Capacity", "[Capacity] >= 1 AND [Capacity] <= 500");

                            t.HasCheckConstraint("CK_Halls_Price", "[Price] >= 0 AND [Price] <= 10000");
                        });
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.HallServices", b =>
                {
                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("HallId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HallServices", (string)null);
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Services", null, t =>
                        {
                            t.HasCheckConstraint("CK_Services_Price", "[Price] >= 0 AND [Price] <= 10000");
                        });
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookingManagmentSystem.Domain.Entities.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.BookingServices", b =>
                {
                    b.HasOne("BookingManagmentSystem.Domain.Entities.Booking", "Booking")
                        .WithMany("SelectedServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingManagmentSystem.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.HallServices", b =>
                {
                    b.HasOne("BookingManagmentSystem.Domain.Entities.Hall", "Hall")
                        .WithMany("HallServices")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingManagmentSystem.Domain.Entities.Service", "Service")
                        .WithMany("HallServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Booking", b =>
                {
                    b.Navigation("SelectedServices");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Hall", b =>
                {
                    b.Navigation("HallServices");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Service", b =>
                {
                    b.Navigation("HallServices");
                });
#pragma warning restore 612, 618
        }
    }
}
