// <auto-generated />
using BookingManagmentSystem.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingManagmentSystem.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928200809_AddConstraintsAndIndexesForHallAndService")]
    partial class AddConstraintsAndIndexesForHallAndService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Halls", null, t =>
                        {
                            t.HasCheckConstraint("CK_Halls_Capacity", "[Capacity] >= 1 AND [Capacity] <= 500");

                            t.HasCheckConstraint("CK_Halls_Price", "[Price] >= 0 AND [Price] <= 10000");
                        });
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.HallService", b =>
                {
                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("HallId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HallServices", (string)null);
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Services", null, t =>
                        {
                            t.HasCheckConstraint("CK_Services_Price", "[Price] >= 0 AND [Price] <= 10000");
                        });
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.HallService", b =>
                {
                    b.HasOne("BookingManagmentSystem.Domain.Entities.Hall", "Hall")
                        .WithMany("HallServices")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingManagmentSystem.Domain.Entities.Service", "Service")
                        .WithMany("HallServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Hall", b =>
                {
                    b.Navigation("HallServices");
                });

            modelBuilder.Entity("BookingManagmentSystem.Domain.Entities.Service", b =>
                {
                    b.Navigation("HallServices");
                });
#pragma warning restore 612, 618
        }
    }
}
